version: '3.1'

# services:
#     php:
#         build:
#             context: .
#             dockerfile: Dockerfile
#         ports:
#             - '80:80'
#         volumes:
#             - ./src:/var/www/html

#     db:
#         image: 'mariadb'
#         restart: always
        
#         environment:
#             MYSQL_DATABASE: blog
#             MYSQL_ROOT_PASSWORD: password
#             MYSQL_USER: fares
#             MYSQL_PASSWORD: fares
#         ports:
#             - '3306:3306'
#         volumes:
#            # Pour lancer un dump automatiquement au montage du conteneur
#            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql


#     phpmyadmin:
#         image: phpmyadmin
#         restart: always
#         ports:
#             - '8080:80'
#         environment:
#             - PMA_ARBITRARY=1
        
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./src:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: proute_ou_caca
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
            
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        # environment:
        #     MYSQL_USER: user
        #     MYSQL_PASSWORD: test
        #     MYSQL_ROOT_PASSWORD: test
volumes:
    persistent:

        